version: "3.0"

services:
  terraform:
    build:
      context: .
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
    volumes:
      - .:/src
      - ~/.aws:/root/.aws
    working_dir: /src
